name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  # DOC:
  # https://github.com/marketplace/actions/github-action-for-latex
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: IriarteNicolas.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: IriarteNicolas.pdf
          path: IriarteNicolas.pdf
